### ISSUE TITLE
diversities issues

### ISSUE THREAD

**Issue by luizafaraujo** [dcdanko/capalyzer#6]
Hi,
Could you help me with the following questions?

1- could you let us know the main differences between krakenhll and metaphlan?
2- Does Capalizer also calculates beta diversity (Bray-curtis, Jaccard and weighted/unweighted unifrac distances)?
3- In the diversities estimation, how could we use specific taxonomic levels (ex: analyzed by species or gender...)

Thanks!

**Comment by dcdanko** [comment]
1) Krakenhll is a more modern classifier and should be used over metaphlan2

2) Yes. See this file https://github.com/dcdanko/capalyzer/blob/master/capalyzer/packet_parser/dataframes.py

3) This is not yet possible.

I will add answers to (1) and (2) to the docs and add support for (3)

**Comment by luizafaraujo** [comment]
Thank you! I'll wait for the usage in for the answers in the docs.
Best!
